version: "3"
services:
  reverseproxy:
    image: reverseproxy:latest
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-user
      - backend-feed
  backend-user:
    image: udagram-api-user:latest
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: Duongpro102
      POSTGRES_DB: database-2
      POSTGRES_HOST: database-2.convqdnblu3x.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: sontran2002
      JWT_SECRET: helloworld
      URL: "http://localhost:8100"
  backend-feed:
    image: udagram-api-feed:latest
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: Duongpro102
      POSTGRES_DB: database-2
      POSTGRES_HOST: database-2.convqdnblu3x.us-east-1.rds.amazonaws.com
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: sontran2002
      JWT_SECRET: helloworld
      URL: "http://localhost:8100"
  frontend:
    image: udagram-frontend:latest
    ports:
      - "8100:80"
