name: CI Workflow

on: [push, pull_request]

jobs:
  lint-app:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v3
      - name: Lint App
        run: echo "Add linting step here"

  build-docker:
    needs: lint-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: sontm17
          password: Sonpro@102

      - name: Build and push Docker images
        run: |
          docker build -t sontm17/udagram-api-feed:v1 ./udagram-api-feed
          docker push sontm17/udagram-api-feed:v1

          docker build -t sontm17/udagram-api-user:v1 ./udagram-api-user
          docker push sontm17/udagram-api-user:v1

          docker build -t sontm17/udagram-frontend:v1 ./udagram-frontend
          docker push sontm17/udagram-frontend:v1

          docker build -t sontm17/udagram-reverseproxy:v1 ./udagram-reverseproxy
          docker push sontm17/udagram-reverseproxy:v1
